# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-22 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.PositiveSmallIntegerField(choices=[(0, 'Default'), (1, 'Editor'), (2, 'Assigned Editor'), (3, 'Reviewer')], default=0, verbose_name='User Type')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('affiliation', models.CharField(max_length=100, verbose_name='Affiliation')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_staff', models.BooleanField(default=True, verbose_name='Staff')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name_plural': 'Users',
                'verbose_name': 'User',
            },
        ),
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_Date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(blank=True, max_length=75, unique=True, verbose_name='Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name_plural': 'Interests',
                'verbose_name': 'Interest',
            },
        ),
        migrations.CreateModel(
            name='UserAssignedEditor',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Assigned Editors',
                'verbose_name': 'Assigned Editor',
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='UserDefault',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Users',
                'verbose_name': 'User',
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='UserEditor',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Editors',
                'verbose_name': 'Editor',
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='UserReviewer',
            fields=[
            ],
            options={
                'proxy': True,
                'verbose_name_plural': 'Reviewers',
                'verbose_name': 'Reviewer',
            },
            bases=('user.user',),
        ),
    ]
