# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2017-03-02 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_Date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('abstract', models.TextField(max_length=300, verbose_name='Abstract')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Article',
            },
        ),
        migrations.CreateModel(
            name='ArticleDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_Date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Description')),
                ('document', models.FileField(upload_to=journal.models.set_upload_document_path, verbose_name='Document')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Article Document',
                'verbose_name_plural': 'Article Documents',
            },
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_Date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('content', models.CharField(max_length=200, verbose_name='Content')),
                ('users', models.ManyToManyField(to='user.UserEditor', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Journal',
                'verbose_name_plural': 'Journals',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_Date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('period', models.CharField(max_length=100, verbose_name='Period')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal', verbose_name='Journal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Journal', verbose_name='Journal'),
        ),
        migrations.AddField(
            model_name='article',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.Period', verbose_name='Period'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
