# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-22 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_Date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('period', models.CharField(max_length=100, verbose_name='Period')),
                ('content', models.CharField(max_length=200, verbose_name='Content')),
            ],
            options={
                'verbose_name_plural': 'Journals',
                'verbose_name': 'Journal',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_Date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('abstract', models.TextField(max_length=300, verbose_name='Abstract')),
            ],
            options={
                'verbose_name_plural': 'Titles',
                'verbose_name': 'Title',
            },
        ),
    ]
