# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-13 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='journal.Journal', verbose_name='Journal'),
        ),
    ]
