# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-22 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='titles',
            field=models.ManyToManyField(to='journal.Title', verbose_name='Titles'),
        ),
    ]
