# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-22 11:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_journal_titles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_Date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('abstract', models.TextField(max_length=300, verbose_name='Abstract')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Article',
            },
        ),
        migrations.CreateModel(
            name='ArticleDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_Date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('description', models.CharField(max_length=100, null=True, verbose_name='Description')),
                ('document', models.FileField(upload_to=journal.models.set_upload_document_path, verbose_name='Document')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_documents', to='journal.Article', verbose_name='Article')),
            ],
            options={
                'verbose_name': 'Article Document',
                'verbose_name_plural': 'Article Documents',
            },
        ),
        migrations.AlterField(
            model_name='journal',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='title',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='article',
            name='titles',
            field=models.ManyToManyField(to='journal.Title', verbose_name='Titles'),
        ),
    ]
