# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-10-25 11:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create Date')),
                ('update_Date', models.DateTimeField(auto_now=True, verbose_name='Update Date')),
                ('name', models.CharField(blank=True, max_length=75, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Interest',
                'verbose_name_plural': 'Interests',
            },
        ),
    ]
