# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-18 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
